theme: jekyll-theme-minimal
title: Giovanni Jericho Mantuhac
description: Undergraduate @ UC San Diego
logo: https://cdn.discordapp.com/attachments/938667785679147030/1059416385815597096/IMG_7570.jpg
