theme: jekyll-theme-minimal
title: Giovanni Jericho Mantuhac
description: Undergraduate @ UC San Diego
logo: https://media.discordapp.net/attachments/938667785679147030/989092824718934056/1642456092255.jpg
